name: cloud_gallery
description: Ứng dụng Thư Viện Ảnh Trực Tuyến

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.10.0
  firebase_storage: ^11.5.4
  cloud_firestore: ^4.13.0
  image_picker: ^1.0.4
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  share_plus: ^7.2.1
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
